# filepath: netlify.toml
[build]
# Command to build your site
command = """
  rmdir -r public && mkdir public \\
  npx @redocly/cli bundle docs/announcements.yaml docs/comments.yaml docs/posts.yaml docs/icebreakers.yaml --output public/openapi-bundle.yaml && \\
  npx @redocly/cli build-docs public/openapi-bundle.yaml --output public/index.html
  """

# Directory to publish
publish = "public"

[build.environment]
# NODE_VERSION = ">18"
