# filepath: netlify.toml
[build]
# Command to build your site
command = """
  mkdir public && \\ 
  npx @redocly/cli build docs/announcements.yaml -o public/announcements.html && \\
  npx @redocly/cli build docs/comments.yaml -o public/comments.html && \\
  npx @redocly/cli build docs/posts.yaml -o public/posts.html && \\
  npx @redocly/cli build docs/icebreakers.yaml -o public/icebreakers.html
  """

# Directory to publish
publish = "public"

[build.environment]
# NODE_VERSION = ">18"
