openapi: "3.0.3"
info:
  title: ALU-GLOBE Ventures API
  version: "1.1"
  description: API for managing ventures (businesses, startups, or projects) within the ALU-GLOBE platform.
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

paths:
  /ventures:
    post:
      tags:
        - Ventures
      summary: Create a new venture
      description: Submit a new venture with details like name, description, tags, etc.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - category
                - location
                - tags
              properties:
                name:
                  type: string
                  description: The official name of the venture.
                description:
                  type: string
                  description: A brief description of the venture.
                category:
                  type: string
                  description: The venture's category or sector.
                location:
                  type: string
                  description: Country or region where the venture operates.
                tags:
                  type: array
                  items:
                    type: string
                coverImageUrl:
                  type: string
                  format: uri
                logoUrl:
                  type: string
                  format: uri
                socialLinks:
                  type: object
                  additionalProperties:
                    type: string
                    format: uri
                  example:
                    instagram: https://instagram.com/venture
                    linkedIn: https://linkedin.com/in/venture
      responses:
        201:
          description: The created venture
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Venture"

        400:
          $ref: "#/components/responses/BadRequest"

        500:
          $ref: "#/components/responses/InternalServerError"

    get:
      tags:
        - Ventures
      summary: Get all ventures
      description: Retrieve a list of all ventures in the system.
      responses:
        200:
          description: A list of ventures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Venture"

        500:
          $ref: "#/components/responses/InternalServerError"

  /ventures/{ventureId}:
    get:
      tags:
        - Ventures
      summary: Get a specific venture
      description: Fetch details of a single venture by its ID.
      parameters:
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Venture details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Venture"
        404:
          description: Venture not found
        500:
          $ref: "#/components/responses/InternalServerError"

    # put:
    #   tags:
    #     - Ventures
    #   summary: Update a venture
    #   description: Update the information of an existing venture.
    #   parameters:
    #     - name: ventureId
    #       in: path
    #       required: true
    #       schema:
    #         type: string
    #         format: uuid
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: "#/components/schemas/Venture"
    #   responses:
    #     200:
    #       description: Updated venture
    #       content:
    #         application/json:
    #           schema:
    #             $ref: "#/components/schemas/Venture"
    #     400:
    #       $ref: "#/components/responses/BadRequest"
    #     404:
    #       description: Venture not found
    #     500:
    #       $ref: "#/components/responses/InternalServerError"

    delete:
      tags:
        - Ventures
      summary: Delete a venture
      description: Remove a venture from the system.
      parameters:
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Venture deleted successfully
        404:
          description: Venture not found
        500:
          $ref: "#/components/responses/InternalServerError"
  /ventures/{ventureId}/followers:
    post:
      summary: Follow a venture
      responses:
        201:
          description: Follower added successfully
        401:
          $ref: "#/components/responses/UnauthorizedError"

    delete:
      summary: Unfollow a venture
      responses:
        204:
          description: Follower deleted successfully
        403:
          $ref: "#/components/responses/ForbiddenError"

components:
  schemas:
    Venture:
      type: object
      description: Represents a venture in the ALU-GLOBE platform.
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the venture.
        name:
          type: string
        description:
          type: string
        location:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        logoUrl:
          type: string
          format: uri
        coverImageUrl:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        email:
          type: string
          format: email
        mission:
          type: string
        phoneNumber:
          type: string
        website:
          type: string
          format: uri
        yearEstablished:
          type: string
        is_archived:
          type: boolean
        products:
          type: array
          items:
            type: object
        reviews:
          type: integer
        reviewsAverage:
          type: number
        members:
          type: integer
        followers:
          type: integer
        hasFollowed:
          type: boolean
        isMember:
          type: boolean

  responses:
    BadRequest:
      description: Invalid input or malformed request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Bad Request

    # InternalServerError:
    #   description: Server encountered an error
    #   content:
    #     application/json:
    #       schema:
    #         type: object
    #         properties:
    #           message:
    #             type: string
    #             example: Internal Server Error
    UnauthorizedError:
      description: You are not logged in

    ForbiddenError:
      description: You can't perform this action

    InternalServerError:
      description: Something went wrong. Please try later
